website: "&eVul hier je website in"
resource-pack: "&bVul hier de download url in"
anti-scheld-msg: "&6Example scheld msg"
badwords:
- kanker
- lul
- penis
- kaka
- homo
- kut
- tering
- kak
- suck
- snul
- dom
- LUL
- PENIS
- KAKA
- HOMO
- KUT
- TERING
- ebola
- EBOLA
- KAK
- SUCK
- SNUL
- DOM
- NOOB
- noob
 - vul zo je scheld woorden in